PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
PubkeyAuthentication yes
PermitRootLogin no
AllowUsers __VPN_ADMIN_USER__
MaxAuthTries 3
LoginGraceTime 30
